apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillpulse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/uttamtripathi-p/github-actions-kubernetes-hackathon.git
    targetRevision: HEAD
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: skillpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
